# ci.yml版本
version: 2
# 选择默认使用的构建配置，此处选择的构建配置必修在profiles.name中有对应的配置。
build:
  profile: main
# 配置构建配置，可同时配置多个构建配置。
profiles:
  # main的构建配置。
  # 构建配置的名称，必须是唯一的标识符，不可重复。建议为每个场景选择具有明确含义的名称，例如 "dev"、"prod" 或 "test" 等，以便更容易理解其用途。
  - name: main
    # 构建阶段任务执行的命令，可以配置项目构建命令、移动构建产出到构建目录等操作。
    # 建议使用 "sh build.sh" 的形式，并将相关命令写入 "build.sh" 脚本中。这样可以使配置更清晰和易于维护。
    command: sh build.sh
    # 构建使用的用户，默认使用 "root" 用户。
    user: "hao_root"
    # 构建环境的操作系统。比如：centos-7、ubuntu-18.04 等。
    runs-on: centos-7
    # 构建环境。可配置多种。如果没有配置环境需要删除该配置项。
    with:
      maven-version: "3.8.1"
      jdk-version: "8"
    # 构建产出的位置，可同时配置多个产出的位置。构建产出将会被打包上传到仓库，以便其他人下载并使用。
    output:
      # - output/a.out：打包项目根目录下的output目录下的a.out文件。
      # - foo/*：通过通配符指定的文件。示例中配置打包foo目录下除以 . 开头的隐藏文件以外的所有文件。
      # - foo：打包foo目录下的所有文件，包括以 . 开头的隐藏文件。
      - output/a.out
      - foo/*
  # dev的构建配置
  - name: dev
    command: sh build.sh
    user: "hao_root"
    runs-on: centos-7
    with:
      maven-version: "3"
      jdk-version: "14"
    # 构建产出目录
    output:
      - output/*