server:
  port: 8080

spring:
  application:
    name: spring-security-iam

  # 数据库配置
  datasource:
    # 注意在数据库连接URL中添加了allowPublicKeyRetrieval=true参数，以解决"Public Key Retrieval is not allowed"异常。 这个错误通常发生在MySQL 8.0+版本中，当使用SSL连接时，MySQL服务器要求客户端进行公钥检索，但客户端配置不允许这样做。添加allowPublicKeyRetrieval=true参数允许客户端从服务器检索公钥，从而建立安全的连接。
    url: jdbc:mysql://localhost:3306/hao_db4?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # 数据初始化配置
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# JWT配置
jwt:
  secret: myVeryLongAndSecureJWTSecretKeyForHS512AlgorithmWithMoreThan64Characters123456789012345678901234567890
  access-token-expiration: 1800000  # 30分钟
  refresh-token-expiration: 604800000  # 7天

# 超级管理员配置
super-admin:
  username: "superadmin"
  password: "SuperAdmin123!@#"

# 日志配置
logging:
  level:
    com.example: debug
    org.springframework.security: debug